/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaPrincipal;
import VistaPrincipal.vEstudiantes;
/**
 *
 * @author Bryan
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
         this.setTitle("Matriculacion estudiante "); 
        this.setExtendedState(this.MAXIMIZED_BOTH);
        //Panel.setBorder(new imagenfondo());
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        mSF = new javax.swing.JMenuBar();
        mParametros = new javax.swing.JMenu();
        mpClientes = new javax.swing.JMenuItem();
        mpCategorias = new javax.swing.JMenuItem();
        mpProductos = new javax.swing.JMenuItem();
        mpVendedores = new javax.swing.JMenuItem();
        mpTipoVenta = new javax.swing.JMenuItem();
        mpTipoVenta1 = new javax.swing.JMenuItem();
        mFacturacion = new javax.swing.JMenu();
        mReportes = new javax.swing.JMenu();
        mpClientes1 = new javax.swing.JMenuItem();
        mpCategorias1 = new javax.swing.JMenuItem();
        mpProductos1 = new javax.swing.JMenuItem();
        mpVendedores1 = new javax.swing.JMenuItem();
        mpTipoVenta2 = new javax.swing.JMenuItem();
        mpTipoVenta3 = new javax.swing.JMenuItem();
        mSeguridad = new javax.swing.JMenu();
        msResetearClave = new javax.swing.JMenuItem();
        msUsuarios = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        maAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 710));

        mParametros.setText("Parametros");

        mpClientes.setText("Estudiantes");
        mpClientes.setToolTipText("");
        mpClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpClientesActionPerformed(evt);
            }
        });
        mParametros.add(mpClientes);

        mpCategorias.setText("Docentes");
        mpCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpCategoriasActionPerformed(evt);
            }
        });
        mParametros.add(mpCategorias);

        mpProductos.setText("Asignaturas");
        mpProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpProductosActionPerformed(evt);
            }
        });
        mParametros.add(mpProductos);

        mpVendedores.setText("Carreras");
        mpVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpVendedoresActionPerformed(evt);
            }
        });
        mParametros.add(mpVendedores);

        mpTipoVenta.setText("Cursos");
        mpTipoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpTipoVentaActionPerformed(evt);
            }
        });
        mParametros.add(mpTipoVenta);

        mpTipoVenta1.setText("Paralelos");
        mpTipoVenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpTipoVenta1ActionPerformed(evt);
            }
        });
        mParametros.add(mpTipoVenta1);

        mSF.add(mParametros);

        mFacturacion.setText("Matricula");
        mSF.add(mFacturacion);

        mReportes.setText("Reportes");

        mpClientes1.setText("Estudiantes");
        mpClientes1.setToolTipText("");
        mpClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpClientes1ActionPerformed(evt);
            }
        });
        mReportes.add(mpClientes1);

        mpCategorias1.setText("Docentes");
        mpCategorias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpCategorias1ActionPerformed(evt);
            }
        });
        mReportes.add(mpCategorias1);

        mpProductos1.setText("Asignaturas");
        mpProductos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpProductos1ActionPerformed(evt);
            }
        });
        mReportes.add(mpProductos1);

        mpVendedores1.setText("Carreras");
        mpVendedores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpVendedores1ActionPerformed(evt);
            }
        });
        mReportes.add(mpVendedores1);

        mpTipoVenta2.setText("Cursos");
        mpTipoVenta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpTipoVenta2ActionPerformed(evt);
            }
        });
        mReportes.add(mpTipoVenta2);

        mpTipoVenta3.setText("Paralelos");
        mpTipoVenta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpTipoVenta3ActionPerformed(evt);
            }
        });
        mReportes.add(mpTipoVenta3);

        mSF.add(mReportes);

        mSeguridad.setText("Seguridad");

        msResetearClave.setText("Resetear clave");
        msResetearClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msResetearClaveActionPerformed(evt);
            }
        });
        mSeguridad.add(msResetearClave);

        msUsuarios.setText("Usuarios");
        msUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msUsuariosActionPerformed(evt);
            }
        });
        mSeguridad.add(msUsuarios);

        mSF.add(mSeguridad);

        mAyuda.setText("Ayuda");

        maAcercaDe.setText("Acerca de...");
        maAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maAcercaDeActionPerformed(evt);
            }
        });
        mAyuda.add(maAcercaDe);

        mSF.add(mAyuda);

        setJMenuBar(mSF);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mpClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpClientesActionPerformed
         vEstudiantes p=new vEstudiantes();
        this.Panel.add(p);
        p.show();
    }//GEN-LAST:event_mpClientesActionPerformed

    private void mpCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpCategoriasActionPerformed
       
    }//GEN-LAST:event_mpCategoriasActionPerformed

    private void mpProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpProductosActionPerformed
       
    }//GEN-LAST:event_mpProductosActionPerformed

    private void mpVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpVendedoresActionPerformed
        
    }//GEN-LAST:event_mpVendedoresActionPerformed

    private void mpTipoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpTipoVentaActionPerformed
       
    }//GEN-LAST:event_mpTipoVentaActionPerformed

    private void msResetearClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msResetearClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msResetearClaveActionPerformed

    private void msUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msUsuariosActionPerformed

    private void maAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maAcercaDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maAcercaDeActionPerformed

    private void mpTipoVenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpTipoVenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpTipoVenta1ActionPerformed

    private void mpClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpClientes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpClientes1ActionPerformed

    private void mpCategorias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpCategorias1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpCategorias1ActionPerformed

    private void mpProductos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpProductos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpProductos1ActionPerformed

    private void mpVendedores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpVendedores1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpVendedores1ActionPerformed

    private void mpTipoVenta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpTipoVenta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpTipoVenta2ActionPerformed

    private void mpTipoVenta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpTipoVenta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpTipoVenta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenu mFacturacion;
    private javax.swing.JMenu mParametros;
    private javax.swing.JMenu mReportes;
    private javax.swing.JMenuBar mSF;
    private javax.swing.JMenu mSeguridad;
    private javax.swing.JMenuItem maAcercaDe;
    private javax.swing.JMenuItem mpCategorias;
    private javax.swing.JMenuItem mpCategorias1;
    private javax.swing.JMenuItem mpClientes;
    private javax.swing.JMenuItem mpClientes1;
    private javax.swing.JMenuItem mpProductos;
    private javax.swing.JMenuItem mpProductos1;
    private javax.swing.JMenuItem mpTipoVenta;
    private javax.swing.JMenuItem mpTipoVenta1;
    private javax.swing.JMenuItem mpTipoVenta2;
    private javax.swing.JMenuItem mpTipoVenta3;
    private javax.swing.JMenuItem mpVendedores;
    private javax.swing.JMenuItem mpVendedores1;
    private javax.swing.JMenuItem msResetearClave;
    private javax.swing.JMenuItem msUsuarios;
    // End of variables declaration//GEN-END:variables
}
